apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "federid.labels" . | nindent 4 }}
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: {{ .Values.namespace }}