apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "federid.labels" . | nindent 4 }}
  name: federid-webhook
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      federid.io/system: "true"
