apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "federid.labels" . | nindent 4 }}
  name: federid-webhook-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    federid.io/system: "true"
